name: Self-test

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [labeled]
  workflow_dispatch:

jobs:
  selftest:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install sigstore-python
        run: pip install sigstore
      - name: conformance test sigstore-python
        uses: ./
        id: sigstore-conformance
        if: github.event_name != 'pull_request' || contains(github.event.pull_request.labels.*.name, 'safe to test')
        with:
          entrypoint: ${{ github.workspace }}/sigstore-python-conformance
