name: Self-test

on:
  push:
    branches:
      - main
  issue_comment:
    types: [created, edited]
  workflow_dispatch:

jobs:
  selftest:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install sigstore-python
        run: pip install sigstore
      - name: conformance test sigstore-python
        uses: ./
        id: sigstore-conformance
        with:
          entrypoint: ${{ github.workspace }}/sigstore-python-conformance
